  # -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require './lib/motioncv'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'motioncv'
end
